flyway.user=postgres
flyway.password=postgres
flyway.schemas=public
flyway.url=jdbc:postgresql://localhost:5432/ordering
flyway.locations=classpath:db/migrations
flyway.cleanDisabled=false

# Command
#./gradlew flywayInfo -Dflyway.configFiles=flyway.conf

# Command skipTest
#./gradlew -x check build flywayInfo -Dflyway.configFiles=flyway.conf
#./gradlew -x check build flywayMigrate -Dflyway.configFiles=flyway.conf
#./gradlew flywayClean -Dflyway.configFiles=flyway.conf